# Site settings
title: radaiming's nonsense
description: > # this means to ignore newlines until "baseurl:"
    nothing special
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://radaiming.github.io/" # the base hostname & protocol for your site
github_username:  radaiming

# Build settings
markdown: kramdown
hard_wrap: false
